### ISSUE TITLE
The reply to this interaction has already been sent or deferred.

### ISSUE THREAD

**Issue by AsianHyun** [barisbored/slash-level#4]
steps for reproducing :
    1. git cloning this repository
    2. npm run build
    3. npm start
    4. use /rank command

---

/home/ubuntu/level-bot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:102
    if (this.deferred || this.replied) throw new DiscordjsError(ErrorCodes.InteractionAlreadyReplied);
                                             ^

Error [InteractionAlreadyReplied]: The reply to this interaction has already been sent or deferred.
    at ChatInputCommandInteraction.reply (/home/ubuntu/level-bot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:102:46)
    at Object.execute (/home/ubuntu/level-bot/dist/commands/rank.js:31:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'InteractionAlreadyReplied'
}

---

I think it can be discord.js@14.6.0's problem

EDIT : not working on discord.js@14.8.0 and discord.js@latest

**Comment by barbarbar338** [comment]
Fixed! Thanks for the report.
